// =============================================================================
// @sentinel-apex/db — public API
// =============================================================================

// Schema tables — re-exported so consumers don't need to drill into sub-paths
export {
  carryActionExecutions,
  carryActionOrderIntents,
  carryExecutionSteps,
  carryActions,
  carryHedgeState,
  carryLegExecutions,
  carryMultiLegPlans,
  carryVenueSnapshots,
  executionGuardrailsConfig,
  executionGuardrailViolations,
  allocatorCurrent,
  allocatorRebalanceBundleEscalationEvents,
  allocatorRebalanceBundleEscalations,
  allocatorRebalanceBundleRecoveryActions,
  allocatorRebalanceBundleResolutionActions,
  allocatorRebalanceBundles,
  allocatorRebalanceCurrent,
  allocatorRebalanceExecutions,
  allocatorRebalanceProposalIntents,
  allocatorRebalanceProposals,
  allocatorRecommendations,
  allocatorRuns,
  allocatorSleeveTargets,
  opsOperators,
  opsOperatorSessions,
  auditEvents,
  orders,
  fills,
  positions,
  portfolioCurrent,
  portfolioSnapshots,
  riskBreaches,
  apyCurrent,
  apyDailySnapshots,
  multiLegEvidenceSummary,
  openPositionPnl,
  performanceReports,
  realizedTradePnl,
  strategyPerformanceSummary,
  vaultCurrent,
  vaultDepositLots,
  vaultDepositors,
  vaultRedemptionRequests,
  vaultSubmissionEvidence,
  vaultSubmissionProfiles,
  executionEvents,
  internalDerivativeCurrent,
  internalDerivativeSnapshots,
  runtimeCommands,
  runtimeMismatchRemediations,
  runtimeMismatches,
  runtimeReconciliationFindings,
  runtimeReconciliationRuns,
  runtimeRecoveryEvents,
  venueConnectorPromotionEvents,
  venueConnectorPromotions,
  venueConnectorSnapshots,
  riskCurrent,
  riskSnapshots,
  runtimeState,
  runtimeWorkerState,
  strategyIntents,
  strategyOpportunityEvaluations,
  strategyOpportunities,
  strategyRuns,
  treasuryActionExecutions,
  treasuryActions,
  treasuryCurrent,
  treasuryRuns,
  treasuryVenueSnapshots,
  cexApiCredentials,
  cexCrossValidations,
  cexImportedTrades,
  cexPnlSnapshots,
  cexTradeImports,
} from './schema/index.js';

// Database client factory + type
export {
  closeAllDatabases,
  createDatabaseConnection,
  getDb,
  resetDatabaseConnectionCache,
} from './client.js';
export type { Database, DatabaseConnection } from './client.js';

export { applyMigrations } from './migrations.js';
