import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

export const vaultCurrent = pgTable(
  'vault_current',
  {
    id: text('id').primaryKey(),
    vaultName: text('vault_name').notNull(),
    strategyId: text('strategy_id').notNull(),
    strategyName: text('strategy_name').notNull(),
    managerName: text('manager_name'),
    managerWalletAddress: text('manager_wallet_address'),
    baseAsset: text('base_asset').notNull(),
    lockPeriodMonths: integer('lock_period_months').notNull(),
    rolling: boolean('rolling').notNull().default(true),
    reassessmentCadenceMonths: integer('reassessment_cadence_months').notNull(),
    targetApyFloorPct: text('target_apy_floor_pct').notNull(),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    strategyIdIdx: index('vault_current_strategy_id_idx').on(t.strategyId),
    updatedAtIdx: index('vault_current_updated_at_idx').on(t.updatedAt),
  }),
);

export const vaultDepositors = pgTable(
  'vault_depositors',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    investorId: text('investor_id').notNull(),
    displayName: text('display_name').notNull(),
    walletAddress: text('wallet_address').notNull(),
    status: text('status').notNull().default('active'),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    investorIdIdx: index('vault_depositors_investor_id_idx').on(t.investorId),
    walletAddressIdx: index('vault_depositors_wallet_address_idx').on(t.walletAddress),
    statusIdx: index('vault_depositors_status_idx').on(t.status),
  }),
);

export const vaultDepositLots = pgTable(
  'vault_deposit_lots',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    vaultId: text('vault_id').notNull(),
    depositorId: uuid('depositor_id').notNull(),
    asset: text('asset').notNull(),
    depositedAmount: text('deposited_amount').notNull(),
    mintedShares: text('minted_shares').notNull(),
    sharePrice: text('share_price').notNull(),
    depositedAt: timestamp('deposited_at', { withTimezone: true }).notNull(),
    lockExpiresAt: timestamp('lock_expires_at', { withTimezone: true }).notNull(),
    redeemedAt: timestamp('redeemed_at', { withTimezone: true }),
    status: text('status').notNull().default('active'),
    note: text('note'),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    vaultIdIdx: index('vault_deposit_lots_vault_id_idx').on(t.vaultId),
    depositorIdIdx: index('vault_deposit_lots_depositor_id_idx').on(t.depositorId),
    statusIdx: index('vault_deposit_lots_status_idx').on(t.status),
    depositedAtIdx: index('vault_deposit_lots_deposited_at_idx').on(t.depositedAt),
    lockExpiresAtIdx: index('vault_deposit_lots_lock_expires_at_idx').on(t.lockExpiresAt),
  }),
);

export const vaultRedemptionRequests = pgTable(
  'vault_redemption_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    vaultId: text('vault_id').notNull(),
    depositorId: uuid('depositor_id').notNull(),
    requestedShares: text('requested_shares').notNull(),
    estimatedAssets: text('estimated_assets').notNull(),
    sharePrice: text('share_price').notNull(),
    requestedAt: timestamp('requested_at', { withTimezone: true }).notNull(),
    eligibleAt: timestamp('eligible_at', { withTimezone: true }).notNull(),
    fulfilledAt: timestamp('fulfilled_at', { withTimezone: true }),
    status: text('status').notNull(),
    note: text('note'),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    vaultIdIdx: index('vault_redemption_requests_vault_id_idx').on(t.vaultId),
    depositorIdIdx: index('vault_redemption_requests_depositor_id_idx').on(t.depositorId),
    statusIdx: index('vault_redemption_requests_status_idx').on(t.status),
    requestedAtIdx: index('vault_redemption_requests_requested_at_idx').on(t.requestedAt),
    eligibleAtIdx: index('vault_redemption_requests_eligible_at_idx').on(t.eligibleAt),
  }),
);

export const vaultSubmissionProfiles = pgTable(
  'vault_submission_profiles',
  {
    id: text('id').primaryKey(),
    submissionName: text('submission_name').notNull(),
    track: text('track').notNull(),
    vaultId: text('vault_id').notNull(),
    strategyId: text('strategy_id').notNull(),
    buildWindowStart: timestamp('build_window_start', { withTimezone: true }).notNull(),
    buildWindowEnd: timestamp('build_window_end', { withTimezone: true }).notNull(),
    cluster: text('cluster').notNull().default('unknown'),
    walletAddress: text('wallet_address'),
    vaultAddress: text('vault_address'),
    cexExecutionUsed: boolean('cex_execution_used').notNull().default(false),
    cexVenues: jsonb('cex_venues').notNull().default([]),
    cexTradeHistoryProvided: boolean('cex_trade_history_provided').notNull().default(false),
    cexReadOnlyApiKeyProvided: boolean('cex_read_only_api_key_provided').notNull().default(false),
    notes: text('notes'),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    trackIdx: index('vault_submission_profiles_track_idx').on(t.track),
    vaultIdIdx: index('vault_submission_profiles_vault_id_idx').on(t.vaultId),
    strategyIdIdx: index('vault_submission_profiles_strategy_id_idx').on(t.strategyId),
    updatedAtIdx: index('vault_submission_profiles_updated_at_idx').on(t.updatedAt),
  }),
);

export const vaultSubmissionEvidence = pgTable(
  'vault_submission_evidence',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    submissionId: text('submission_id')
      .notNull()
      .references(() => vaultSubmissionProfiles.id),
    evidenceType: text('evidence_type').notNull(),
    status: text('status').notNull().default('recorded'),
    source: text('source').notNull().default('manual'),
    label: text('label').notNull(),
    summary: text('summary'),
    reference: text('reference'),
    url: text('url'),
    capturedAt: timestamp('captured_at', { withTimezone: true }),
    withinBuildWindow: boolean('within_build_window').notNull().default(false),
    notes: text('notes'),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    submissionIdIdx: index('vault_submission_evidence_submission_id_idx').on(t.submissionId),
    evidenceTypeIdx: index('vault_submission_evidence_type_idx').on(t.evidenceType),
    statusIdx: index('vault_submission_evidence_status_idx').on(t.status),
    capturedAtIdx: index('vault_submission_evidence_captured_at_idx').on(t.capturedAt),
    updatedAtIdx: index('vault_submission_evidence_updated_at_idx').on(t.updatedAt),
  }),
);

// =============================================================================
// Realized APY Tracking Tables
// =============================================================================

export const realizedTradePnl = pgTable(
  'realized_trade_pnl',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tradeId: text('trade_id').notNull().unique(),
    positionId: text('position_id'),
    sleeveId: text('sleeve_id').notNull(),
    venueId: text('venue_id').notNull(),
    asset: text('asset').notNull(),
    side: text('side').notNull(),
    instrumentType: text('instrument_type').notNull().default('perpetual'),
    entryPrice: text('entry_price').notNull(),
    exitPrice: text('exit_price').notNull(),
    size: text('size').notNull(),
    notionalUsd: text('notional_usd').notNull(),
    grossPnl: text('gross_pnl').notNull(),
    fundingPnl: text('funding_pnl').notNull().default('0'),
    feeCost: text('fee_cost').notNull(),
    netPnl: text('net_pnl').notNull(),
    openedAt: timestamp('opened_at', { withTimezone: true }).notNull(),
    closedAt: timestamp('closed_at', { withTimezone: true }).notNull(),
    holdingPeriodDays: text('holding_period_days').notNull(),
    executionReference: text('execution_reference'),
    confirmed: boolean('confirmed').notNull().default(false),
    confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tradeIdIdx: index('realized_trade_pnl_trade_id_idx').on(t.tradeId),
    positionIdIdx: index('realized_trade_pnl_position_id_idx').on(t.positionId),
    sleeveIdIdx: index('realized_trade_pnl_sleeve_id_idx').on(t.sleeveId),
    assetIdx: index('realized_trade_pnl_asset_idx').on(t.asset),
    closedAtIdx: index('realized_trade_pnl_closed_at_idx').on(t.closedAt),
    confirmedIdx: index('realized_trade_pnl_confirmed_idx').on(t.confirmed, t.closedAt),
  }),
);

export const apyDailySnapshots = pgTable(
  'apy_daily_snapshots',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    snapshotDate: text('snapshot_date').notNull(),
    sleeveId: text('sleeve_id').notNull(),
    strategyId: text('strategy_id').notNull(),
    totalCapitalUsd: text('total_capital_usd').notNull(),
    deployedCapitalUsd: text('deployed_capital_usd').notNull(),
    idleCapitalUsd: text('idle_capital_usd').notNull(),
    dailyPnlUsd: text('daily_pnl_usd').notNull(),
    dailyReturnPct: text('daily_return_pct').notNull(),
    cumulativePnlUsd: text('cumulative_pnl_usd').notNull(),
    cumulativeReturnPct: text('cumulative_return_pct').notNull(),
    realizedApy7d: text('realized_apy_7d'),
    realizedApy30d: text('realized_apy_30d'),
    realizedApyLifetime: text('realized_apy_lifetime'),
    tradesClosedCount: integer('trades_closed_count').notNull().default(0),
    tradesWinningCount: integer('trades_winning_count').notNull().default(0),
    tradesLosingCount: integer('trades_losing_count').notNull().default(0),
    avgTradePnlUsd: text('avg_trade_pnl_usd'),
    avgHoldingPeriodDays: text('avg_holding_period_days'),
    fundingPnlUsd: text('funding_pnl_usd').notNull().default('0'),
    pricePnlUsd: text('price_pnl_usd').notNull().default('0'),
    feeCostUsd: text('fee_cost_usd').notNull().default('0'),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    dateSleeveUnique: index('apy_daily_snapshots_date_sleeve_idx').on(t.snapshotDate, t.sleeveId),
    dateIdx: index('apy_daily_snapshots_date_idx').on(t.snapshotDate),
    sleeveIdIdx: index('apy_daily_snapshots_sleeve_id_idx').on(t.sleeveId),
    strategyIdIdx: index('apy_daily_snapshots_strategy_id_idx').on(t.strategyId),
  }),
);

export const apyCurrent = pgTable(
  'apy_current',
  {
    id: text('id').primaryKey(),
    sleeveId: text('sleeve_id').notNull(),
    strategyId: text('strategy_id').notNull(),
    latestSnapshotId: uuid('latest_snapshot_id').references(() => apyDailySnapshots.id),
    latestSnapshotDate: text('latest_snapshot_date'),
    realizedApy7d: text('realized_apy_7d'),
    realizedApy30d: text('realized_apy_30d'),
    realizedApyLifetime: text('realized_apy_lifetime'),
    targetApyPct: text('target_apy_pct').notNull(),
    projectedApyPct: text('projected_apy_pct'),
    targetMet: boolean('target_met'),
    targetGapPct: text('target_gap_pct'),
    totalTradesClosed: integer('total_trades_closed').notNull().default(0),
    totalPnlUsd: text('total_pnl_usd').notNull().default('0'),
    totalFundingPnlUsd: text('total_funding_pnl_usd').notNull().default('0'),
    totalFeesUsd: text('total_fees_usd').notNull().default('0'),
    avgTradePnlUsd: text('avg_trade_pnl_usd'),
    winRatePct: text('win_rate_pct'),
    firstTradeAt: timestamp('first_trade_at', { withTimezone: true }),
    calculationBasis: text('calculation_basis').notNull().default('insufficient_data'),
    metadata: jsonb('metadata').notNull().default({}),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    sleeveIdIdx: index('apy_current_sleeve_id_idx').on(t.sleeveId),
    strategyIdIdx: index('apy_current_strategy_id_idx').on(t.strategyId),
  }),
);

export const strategyPerformanceSummary = pgTable(
  'strategy_performance_summary',
  {
    id: text('id').primaryKey(),
    strategyId: text('strategy_id').notNull(),
    sleeveId: text('sleeve_id').notNull(),
    period1d: jsonb('period_1d').notNull().default({}),
    period7d: jsonb('period_7d').notNull().default({}),
    period30d: jsonb('period_30d').notNull().default({}),
    period90d: jsonb('period_90d').notNull().default({}),
    periodLifetime: jsonb('period_lifetime').notNull().default({}),
    currentApy: text('current_apy'),
    targetApy: text('target_apy').notNull(),
    targetStatus: text('target_status').notNull().default('unknown'),
    lastUpdatedAt: timestamp('last_updated_at', { withTimezone: true }).notNull().defaultNow(),
    lastTradeAt: timestamp('last_trade_at', { withTimezone: true }),
    metadata: jsonb('metadata').notNull().default({}),
  },
  (t) => ({
    strategyIdIdx: index('strategy_performance_summary_strategy_id_idx').on(t.strategyId),
    sleeveIdIdx: index('strategy_performance_summary_sleeve_id_idx').on(t.sleeveId),
  }),
);

export const openPositionPnl = pgTable(
  'open_position_pnl',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    positionId: text('position_id').notNull().unique(),
    sleeveId: text('sleeve_id').notNull(),
    venueId: text('venue_id').notNull(),
    asset: text('asset').notNull(),
    side: text('side').notNull(),
    instrumentType: text('instrument_type').notNull().default('perpetual'),
    entryPrice: text('entry_price').notNull(),
    currentPrice: text('current_price').notNull(),
    size: text('size').notNull(),
    notionalUsd: text('notional_usd').notNull(),
    unrealizedPnl: text('unrealized_pnl').notNull(),
    unrealizedPnlPct: text('unrealized_pnl_pct').notNull(),
    fundingPnl: text('funding_pnl').notNull().default('0'),
    feeCost: text('fee_cost').notNull().default('0'),
    netUnrealizedPnl: text('net_unrealized_pnl').notNull(),
    openedAt: timestamp('opened_at', { withTimezone: true }).notNull(),
    holdingPeriodDays: text('holding_period_days').notNull(),
    projectedAnnualFunding: text('projected_annual_funding'),
    projectedApy: text('projected_apy'),
    metadata: jsonb('metadata').notNull().default({}),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    positionIdIdx: index('open_position_pnl_position_id_idx').on(t.positionId),
    sleeveIdIdx: index('open_position_pnl_sleeve_id_idx').on(t.sleeveId),
    assetIdx: index('open_position_pnl_asset_idx').on(t.asset),
  }),
);
